-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Page Visits Table
create table if not exists page_visits (
  id uuid default uuid_generate_v4() primary key,
  path text not null,
  visitor_id text,
  user_id uuid references auth.users(id),
  metadata jsonb,
  visited_at timestamp with time zone default now()
);

-- RLS for page_visits (Allow insert for everyone, select for admins only usually)
alter table page_visits enable row level security;
drop policy if exists "Allow anonymous insert" on page_visits;
create policy "Allow anonymous insert" on page_visits for insert with check (true);
drop policy if exists "Allow admin select" on page_visits;
create policy "Allow admin select" on page_visits for select using (true);

-- 2. Domains Table
create table if not exists domains (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id),
  domain_name text not null,
  extension text not null,
  status text default 'pending', -- pending, active, expired
  expiry_date timestamp with time zone,
  auto_renew boolean default false,
  created_at timestamp with time zone default now()
);

alter table domains enable row level security;
drop policy if exists "Users can view own domains" on domains;
create policy "Users can view own domains" on domains for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own domains" on domains;
create policy "Users can insert own domains" on domains for insert with check (auth.uid() = user_id);
drop policy if exists "Admins can view all domains" on domains;
create policy "Admins can view all domains" on domains for select using (true);
drop policy if exists "Admins can update domains" on domains;
create policy "Admins can update domains" on domains for update using (true);

-- 3. Domain Transactions (Wallet)
create table if not exists domain_transactions (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id),
  transaction_type text not null, -- purchase, refund, deposit
  amount numeric not null,
  currency text default 'SAR',
  payment_status text default 'pending', -- pending, completed, failed
  years_purchased integer,
  notes text,
  created_at timestamp with time zone default now()
);

alter table domain_transactions enable row level security;
drop policy if exists "Users can view own transactions" on domain_transactions;
create policy "Users can view own transactions" on domain_transactions for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own transactions" on domain_transactions;
create policy "Users can insert own transactions" on domain_transactions for insert with check (auth.uid() = user_id);
drop policy if exists "Admins can view all transactions" on domain_transactions;
create policy "Admins can view all transactions" on domain_transactions for select using (true);

-- 4. Admins Table
create table if not exists admins (
  id uuid default uuid_generate_v4() primary key,
  email text unique not null,
  password text not null, -- Added password column
  role text default 'admin',
  created_at timestamp with time zone default now()
);

-- Ensure password column exists if table was created previously without it
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'admins' and column_name = 'password') then
    alter table admins add column password text;
  end if;
end $$;

-- Insert initial admin (Safe insert/update)
insert into admins (email, password, role)
values ('oooomar896@gmail.com', 'Omar@2597798', 'super_admin')
on conflict (email) do update 
set password = 'Omar@2597798', role = 'super_admin';

alter table admins enable row level security;
drop policy if exists "Read admins" on admins;
create policy "Read admins" on admins for select using (true);

-- 5. Generated Projects (Client Requests)
-- Note: Assuming table exists as bigint based on error. Updating definition to match.
create table if not exists generated_projects (
  id bigint generated by default as identity primary key,
  user_email text not null,
  project_name text,
  project_type text,
  description text,
  features jsonb,
  status text default 'pending_review',
  project_stage text default 'analysis',
  files jsonb,
  budget text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table generated_projects enable row level security;
drop policy if exists "Users view own projects" on generated_projects;
create policy "Users view own projects" on generated_projects for select using (true);
drop policy if exists "Insert own projects" on generated_projects;
create policy "Insert own projects" on generated_projects for insert with check (true);
drop policy if exists "Admin manage all projects" on generated_projects;
create policy "Admin manage all projects" on generated_projects for all using (true);


-- 6. Contracts
create table if not exists contracts (
  id uuid default uuid_generate_v4() primary key,
  user_email text not null,
  project_id bigint references generated_projects(id), -- Changed to bigint to match
  title text not null,
  body text,
  amount text,
  status text default 'pending',
  signed_at timestamp with time zone,
  pdf_url text,
  created_at timestamp with time zone default now()
);

alter table contracts enable row level security;
drop policy if exists "Users view own contracts" on contracts;
create policy "Users view own contracts" on contracts for select using (true); -- Simplified, ideally filtered by email
drop policy if exists "Admin manage contracts" on contracts;
create policy "Admin manage contracts" on contracts for all using (true);
