[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[headers]]
  for = "/*"
  values = {
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:;"
  }

[[headers]]
  for = "*.html"
  values = {
    Cache-Control = "public, max-age=0, must-revalidate"
  }

[[headers]]
  for = "*.css"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[headers]]
  for = "*.js"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[headers]]
  for = "*.png"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[headers]]
  for = "*.jpg"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[headers]]
  for = "*.jpeg"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[headers]]
  for = "*.gif"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[headers]]
  for = "*.svg"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[headers]]
  for = "*.ico"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[headers]]
  for = "*.woff"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[headers]]
  for = "*.woff2"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[headers]]
  for = "*.ttf"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[headers]]
  for = "*.eot"
  values = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

[[redirects]]
  from = "/cv"
  to = "/"
  status = 301

[[redirects]]
  from = "/portfolio"
  to = "/"
  status = 301

[[redirects]]
  from = "/store"
  to = "/"
  status = 301

[[redirects]]
  from = "/projects"
  to = "/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for the portfolio
[context.production.environment]
  SITE_NAME = "Omar Hamid Portfolio Store"
  SITE_DESCRIPTION = "Technical Portfolio Store - Flutter, React Native, Odoo Developer"
  CONTACT_EMAIL = "oooomar123450@gmail.com"
  CONTACT_PHONE = "+966-55-853-9717"

[context.deploy-preview.environment]
  SITE_NAME = "Omar Hamid Portfolio Store (Preview)"
  SITE_DESCRIPTION = "Technical Portfolio Store - Flutter, React Native, Odoo Developer"
  CONTACT_EMAIL = "oooomar123450@gmail.com"
  CONTACT_PHONE = "+966-55-853-9717" 