-- Create Admins Table
create table public.admins (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text unique not null,
  password text not null, -- In production, use hashed passwords!
  role text default 'admin'
);

-- Enable RLS
alter table public.admins enable row level security;

-- Policy to allow read/write for demo
create policy "Allow public read access to admins" on public.admins for select using (true);
create policy "Allow public write access to admins" on public.admins for all using (true);

-- Insert User Admin
insert into public.admins (email, password, role)
values ('oooomar123450@gmail.com', 'Omar@2597798', 'super_admin');

-- FIX PREVIOUS POLICIES (Important for Add/Edit to work)
drop policy if exists "Enable read access for all users" on public.projects;
drop policy if exists "Enable read access for all users" on public.news;

-- Re-create policies allowing FULL ACCESS for app usage
create policy "Enable all access for projects" on public.projects for all using (true);
create policy "Enable all access for news" on public.news for all using (true);
create policy "Enable all access for leads" on public.leads for all using (true);
