-- Create table for Contact Messages
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  subject text,
  message text,
  read boolean default false,
  replies jsonb default '[]'::jsonb
);

-- Create table for Projects
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  category text,
  description text,
  link text,
  image_url text,
  status text default 'published'
);

-- Create table for News
create table public.news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text,
  image_url text,
  link text,
  date date default CURRENT_DATE
);

-- Create table for Users/Leads
create table public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text unique,
  role text default 'user',
  generated_projects jsonb default '[]'::jsonb
);

-- Enable Row Level Security (RLS)
alter table public.messages enable row level security;
alter table public.projects enable row level security;
alter table public.news enable row level security;
alter table public.leads enable row level security;

-- Create policies (Open for demo purposes, restrict in production)
create policy "Enable read access for all users" on public.projects for select using (true);
create policy "Enable read access for all users" on public.news for select using (true);
create policy "Enable insert for all users" on public.messages for insert with check (true);
create policy "Enable all access for service role" on public.messages for all using (true);
