-- Create Skills Table
create table public.skills (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    category text,
    level integer default 50,
    icon text -- Optional: for future use
);

-- Create Activities Log Table
create table public.activities (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    type text not null, -- 'create', 'update', 'delete', 'login'
    message text not null,
    admin_email text
);

-- Create Settings Table (Single row expected)
create table public.settings (
    id bigint generated by default as identity primary key,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    site_name text default 'عمر التقني - Portfolio',
    admin_email text,
    enable_ai_builder boolean default true,
    maintenance_mode boolean default false,
    notifications_enabled boolean default true
);

-- Create Generated Projects Table (For detailed AI project analytics)
create table public.generated_projects (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_email text,
    project_name text,
    project_type text,
    features jsonb, -- List of selected features
    description text,
    status text default 'pending'
);

-- Enable RLS
alter table public.skills enable row level security;
alter table public.activities enable row level security;
alter table public.settings enable row level security;
alter table public.generated_projects enable row level security;

-- Policies (Permissive for development/demo)
create policy "Allow all access to skills" on public.skills for all using (true);
create policy "Allow all access to activities" on public.activities for all using (true);
create policy "Allow all access to settings" on public.settings for all using (true);
create policy "Allow all access to generated_projects" on public.generated_projects for all using (true);

-- Insert Default Settings
insert into public.settings (site_name, admin_email, enable_ai_builder)
values ('عمر التقني - Portfolio', 'oooomar123450@gmail.com', true);
