-- ============================================
-- SUPABASE COMPLETE DATABASE SCHEMA
-- منصة باكورة أعمال (Bacura Business Platform)
-- ============================================
-- تاريخ الإنشاء: 2026-01-13
-- الإصدار: 2.0.0
-- المطور: Omar Hamid Al-Adini
-- ============================================

-- ============================================
-- SECTION 1: EXTENSIONS & SETUP
-- ============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enable pg_cron for scheduled tasks (if available)
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- ============================================
-- SECTION 2: CORE TABLES
-- ============================================

-- --------------------------------------------
-- 2.1 Users & Authentication
-- --------------------------------------------

-- Users table (extends auth.users)
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role TEXT DEFAULT 'user', -- 'user', 'admin', 'provider', 'driver'
  phone TEXT,
  avatar_url TEXT,
  metadata JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Admins table (legacy, consider migrating to users table)
CREATE TABLE IF NOT EXISTS public.admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL, -- Note: Use hashed passwords in production!
  role TEXT DEFAULT 'admin'
);

-- Leads table (potential customers)
CREATE TABLE IF NOT EXISTS public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  name TEXT,
  email TEXT UNIQUE,
  role TEXT DEFAULT 'user',
  generated_projects JSONB DEFAULT '[]'::JSONB
);

-- --------------------------------------------
-- 2.2 Content Management
-- --------------------------------------------

-- Projects table (portfolio projects)
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  category TEXT,
  description TEXT,
  link TEXT,
  image_url TEXT,
  status TEXT DEFAULT 'published',
  technologies JSONB DEFAULT '[]'::JSONB,
  featured BOOLEAN DEFAULT FALSE
);

-- News table
CREATE TABLE IF NOT EXISTS public.news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  content TEXT,
  image_url TEXT,
  link TEXT,
  date DATE DEFAULT CURRENT_DATE,
  published BOOLEAN DEFAULT TRUE
);

-- Skills table
CREATE TABLE IF NOT EXISTS public.skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  category TEXT,
  level INTEGER DEFAULT 50, -- 0-100
  icon TEXT,
  color TEXT
);

-- --------------------------------------------
-- 2.3 Communication
-- --------------------------------------------

-- Messages table (contact form)
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  name TEXT,
  email TEXT,
  subject TEXT,
  message TEXT,
  read BOOLEAN DEFAULT FALSE,
  replies JSONB DEFAULT '[]'::JSONB,
  status TEXT DEFAULT 'new' -- 'new', 'read', 'replied', 'archived'
);

-- Notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  type TEXT DEFAULT 'info', -- 'info', 'success', 'warning', 'error'
  read BOOLEAN DEFAULT FALSE,
  link TEXT,
  metadata JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- SECTION 3: PROJECT BUILDER & REQUESTS
-- ============================================

-- --------------------------------------------
-- 3.1 Generated Projects (AI Builder)
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS public.generated_projects (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  project_name TEXT NOT NULL,
  project_type TEXT NOT NULL,
  description TEXT,
  features JSONB DEFAULT '[]'::JSONB,
  tech_stack JSONB DEFAULT '[]'::JSONB,
  files JSONB DEFAULT '[]'::JSONB,
  analysis JSONB DEFAULT '{}'::JSONB,
  status TEXT DEFAULT 'draft', -- 'draft', 'in_progress', 'completed', 'cancelled'
  stage TEXT DEFAULT 'planning', -- 'planning', 'development', 'testing', 'deployment'
  progress INTEGER DEFAULT 0, -- 0-100
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Project messages (chat for generated projects)
CREATE TABLE IF NOT EXISTS public.project_messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID REFERENCES public.generated_projects(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  sender_type TEXT NOT NULL, -- 'user', 'admin', 'system'
  message TEXT NOT NULL,
  attachments JSONB DEFAULT '[]'::JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- --------------------------------------------
-- 3.2 Service Requests
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS public.service_requests (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  service_type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  budget DECIMAL(10,2),
  deadline DATE,
  status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'in_progress', 'completed', 'rejected'
  priority TEXT DEFAULT 'normal', -- 'low', 'normal', 'high', 'urgent'
  assigned_to UUID REFERENCES auth.users(id),
  metadata JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Request messages/comments
CREATE TABLE IF NOT EXISTS public.request_messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  request_id UUID REFERENCES public.service_requests(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- SECTION 4: DOMAIN MANAGEMENT SYSTEM
-- ============================================

-- --------------------------------------------
-- 4.1 Websites
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS public.websites (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50), -- 'landing', 'booking', 'ecommerce', etc.
  status VARCHAR(50) DEFAULT 'draft', -- 'draft', 'active', 'inactive'
  subdomain VARCHAR(255) UNIQUE,
  custom_domain VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- --------------------------------------------
-- 4.2 Domains
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS public.domains (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  domain_name VARCHAR(255) NOT NULL,
  extension VARCHAR(10) NOT NULL, -- '.com', '.net', '.org', '.sa', etc.
  full_domain VARCHAR(255) UNIQUE NOT NULL, -- domain_name + extension
  status VARCHAR(50) DEFAULT 'active', -- 'active', 'expired', 'pending', 'suspended'
  purchase_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expiry_date TIMESTAMP WITH TIME ZONE NOT NULL,
  auto_renew BOOLEAN DEFAULT FALSE,
  
  -- Provider Information
  provider VARCHAR(50) DEFAULT 'namecheap', -- 'namecheap', 'godaddy', etc.
  provider_domain_id VARCHAR(255),
  
  -- Website Linking
  linked_website_id UUID REFERENCES public.websites(id) ON DELETE SET NULL,
  
  -- Privacy & Security
  whois_privacy BOOLEAN DEFAULT FALSE,
  domain_lock BOOLEAN DEFAULT TRUE,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for domains
CREATE INDEX IF NOT EXISTS idx_domains_user_id ON public.domains(user_id);
CREATE INDEX IF NOT EXISTS idx_domains_status ON public.domains(status);
CREATE INDEX IF NOT EXISTS idx_domains_expiry_date ON public.domains(expiry_date);
CREATE INDEX IF NOT EXISTS idx_domains_full_domain ON public.domains(full_domain);

-- --------------------------------------------
-- 4.3 DNS Records
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS public.dns_records (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  domain_id UUID REFERENCES public.domains(id) ON DELETE CASCADE NOT NULL,
  
  -- DNS Record Details
  record_type VARCHAR(10) NOT NULL, -- 'A', 'AAAA', 'CNAME', 'MX', 'TXT', 'NS'
  host VARCHAR(255) NOT NULL, -- '@', 'www', 'mail', etc.
  value TEXT NOT NULL, -- IP address, domain, or text value
  ttl INTEGER DEFAULT 3600, -- Time to live in seconds
  priority INTEGER, -- For MX records
  
  -- Status
  is_active BOOLEAN DEFAULT TRUE,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for DNS records
CREATE INDEX IF NOT EXISTS idx_dns_records_domain_id ON public.dns_records(domain_id);
CREATE INDEX IF NOT EXISTS idx_dns_records_type ON public.dns_records(record_type);

-- --------------------------------------------
-- 4.4 Domain Transactions
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS public.domain_transactions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  domain_id UUID REFERENCES public.domains(id) ON DELETE SET NULL,
  
  -- Transaction Details
  transaction_type VARCHAR(50) NOT NULL, -- 'purchase', 'renewal', 'transfer'
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(3) DEFAULT 'SAR',
  
  -- Payment Information
  payment_method VARCHAR(50), -- 'credit_card', 'mada', 'apple_pay'
  payment_provider VARCHAR(50), -- 'moyasar', 'stripe'
  payment_id VARCHAR(255),
  payment_status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'completed', 'failed', 'refunded'
  
  -- Additional Info
  years_purchased INTEGER DEFAULT 1,
  notes TEXT,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for domain transactions
CREATE INDEX IF NOT EXISTS idx_domain_transactions_user_id ON public.domain_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_domain_transactions_domain_id ON public.domain_transactions(domain_id);
CREATE INDEX IF NOT EXISTS idx_domain_transactions_status ON public.domain_transactions(payment_status);

-- --------------------------------------------
-- 4.5 Domain Pricing
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS public.domain_pricing (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  extension VARCHAR(10) UNIQUE NOT NULL, -- '.com', '.net', etc.
  
  -- Pricing
  purchase_price DECIMAL(10,2) NOT NULL,
  renewal_price DECIMAL(10,2) NOT NULL,
  transfer_price DECIMAL(10,2),
  currency VARCHAR(3) DEFAULT 'SAR',
  
  -- Availability
  is_available BOOLEAN DEFAULT TRUE,
  is_premium BOOLEAN DEFAULT FALSE,
  
  -- Provider Info
  provider VARCHAR(50) DEFAULT 'namecheap',
  provider_price DECIMAL(10,2), -- Cost from provider
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default pricing
INSERT INTO public.domain_pricing (extension, purchase_price, renewal_price, currency, is_available) VALUES
('.com', 50.00, 50.00, 'SAR', true),
('.net', 55.00, 55.00, 'SAR', true),
('.org', 60.00, 60.00, 'SAR', true),
('.sa', 150.00, 150.00, 'SAR', true),
('.com.sa', 100.00, 100.00, 'SAR', true),
('.info', 45.00, 45.00, 'SAR', true),
('.biz', 50.00, 50.00, 'SAR', true)
ON CONFLICT (extension) DO NOTHING;

-- --------------------------------------------
-- 4.6 Domain Notifications
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS public.domain_notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  domain_id UUID REFERENCES public.domains(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  
  -- Notification Details
  notification_type VARCHAR(50) NOT NULL, -- 'expiry_warning', 'renewal_success', 'dns_change'
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  
  -- Status
  is_read BOOLEAN DEFAULT FALSE,
  sent_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for domain notifications
CREATE INDEX IF NOT EXISTS idx_domain_notifications_user_id ON public.domain_notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_domain_notifications_domain_id ON public.domain_notifications(domain_id);

-- ============================================
-- SECTION 5: ANALYTICS & TRACKING
-- ============================================

-- Page visits tracking
CREATE TABLE IF NOT EXISTS public.page_visits (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  page_path TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  session_id TEXT,
  referrer TEXT,
  user_agent TEXT,
  ip_address TEXT,
  country TEXT,
  city TEXT,
  device_type TEXT, -- 'desktop', 'mobile', 'tablet'
  browser TEXT,
  os TEXT,
  visited_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for page visits
CREATE INDEX IF NOT EXISTS idx_page_visits_page_path ON public.page_visits(page_path);
CREATE INDEX IF NOT EXISTS idx_page_visits_visited_at ON public.page_visits(visited_at);

-- ============================================
-- SECTION 6: ROW LEVEL SECURITY (RLS)
-- ============================================

-- Enable RLS on all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.generated_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.request_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.websites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dns_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domain_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domain_pricing ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domain_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_visits ENABLE ROW LEVEL SECURITY;

-- --------------------------------------------
-- 6.1 Users & Auth Policies
-- --------------------------------------------

-- Users can view their own profile
CREATE POLICY "Users can view own profile" ON public.users
FOR SELECT USING (auth.uid() = id);

-- Users can update their own profile
CREATE POLICY "Users can update own profile" ON public.users
FOR UPDATE USING (auth.uid() = id);

-- Admins can view all users
CREATE POLICY "Admins can view all users" ON public.users
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.users
    WHERE users.id = auth.uid()
    AND users.role = 'admin'
  )
);

-- --------------------------------------------
-- 6.2 Content Policies
-- --------------------------------------------

-- Public read access for projects, news, skills
CREATE POLICY "Public read access" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Public read access" ON public.news FOR SELECT USING (true);
CREATE POLICY "Public read access" ON public.skills FOR SELECT USING (true);

-- Admin full access
CREATE POLICY "Admin full access to projects" ON public.projects FOR ALL USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);
CREATE POLICY "Admin full access to news" ON public.news FOR ALL USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);
CREATE POLICY "Admin full access to skills" ON public.skills FOR ALL USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- --------------------------------------------
-- 6.3 Messages & Notifications Policies
-- --------------------------------------------

-- Anyone can insert messages (contact form)
CREATE POLICY "Anyone can send messages" ON public.messages FOR INSERT WITH CHECK (true);

-- Admins can view and manage messages
CREATE POLICY "Admins can manage messages" ON public.messages FOR ALL USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- Users can view their own notifications
CREATE POLICY "Users view own notifications" ON public.notifications
FOR SELECT USING (auth.uid() = user_id);

-- Users can update their own notifications (mark as read)
CREATE POLICY "Users update own notifications" ON public.notifications
FOR UPDATE USING (auth.uid() = user_id);

-- --------------------------------------------
-- 6.4 Generated Projects Policies
-- --------------------------------------------

-- Users view own projects
CREATE POLICY "Users view own projects" ON public.generated_projects
FOR SELECT USING (auth.uid() = user_id);

-- Users create own projects
CREATE POLICY "Users create own projects" ON public.generated_projects
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users update own projects
CREATE POLICY "Users update own projects" ON public.generated_projects
FOR UPDATE USING (auth.uid() = user_id);

-- Admins view all projects
CREATE POLICY "Admins view all projects" ON public.generated_projects
FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- --------------------------------------------
-- 6.5 Project Messages Policies
-- --------------------------------------------

-- Users view messages for own projects
CREATE POLICY "Users view messages for own projects" ON public.project_messages
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.generated_projects
    WHERE id = project_messages.project_id
    AND user_id = auth.uid()
  )
);

-- Users send messages for own projects
CREATE POLICY "Users send messages for own projects" ON public.project_messages
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.generated_projects
    WHERE id = project_messages.project_id
    AND user_id = auth.uid()
  )
);

-- Admins can view and send all messages
CREATE POLICY "Admins manage all messages" ON public.project_messages
FOR ALL USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- --------------------------------------------
-- 6.6 Domain Policies
-- --------------------------------------------

-- Users view own domains
CREATE POLICY "Users can view own domains" ON public.domains
FOR SELECT USING (auth.uid() = user_id);

-- Users insert own domains
CREATE POLICY "Users can insert own domains" ON public.domains
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users update own domains
CREATE POLICY "Users can update own domains" ON public.domains
FOR UPDATE USING (auth.uid() = user_id);

-- Admins view all domains
CREATE POLICY "Admins can view all domains" ON public.domains
FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- Admins manage all domains
CREATE POLICY "Admins can manage all domains" ON public.domains
FOR ALL USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- --------------------------------------------
-- 6.7 DNS Records Policies
-- --------------------------------------------

-- Users view DNS for own domains
CREATE POLICY "Users can view DNS for own domains" ON public.dns_records
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.domains
    WHERE domains.id = dns_records.domain_id
    AND domains.user_id = auth.uid()
  )
);

-- Users manage DNS for own domains
CREATE POLICY "Users can manage DNS for own domains" ON public.dns_records
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.domains
    WHERE domains.id = dns_records.domain_id
    AND domains.user_id = auth.uid()
  )
);

-- --------------------------------------------
-- 6.8 Domain Transactions Policies
-- --------------------------------------------

-- Users view own transactions
CREATE POLICY "Users can view own transactions" ON public.domain_transactions
FOR SELECT USING (auth.uid() = user_id);

-- Users insert own transactions
CREATE POLICY "Users can insert own transactions" ON public.domain_transactions
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Admins view all transactions
CREATE POLICY "Admins can view all transactions" ON public.domain_transactions
FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- --------------------------------------------
-- 6.9 Domain Pricing Policies (Public Read)
-- --------------------------------------------

CREATE POLICY "Anyone can view pricing" ON public.domain_pricing
FOR SELECT USING (true);

CREATE POLICY "Admins can manage pricing" ON public.domain_pricing
FOR ALL USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- --------------------------------------------
-- 6.10 Domain Notifications Policies
-- --------------------------------------------

CREATE POLICY "Users can view own notifications" ON public.domain_notifications
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own notifications" ON public.domain_notifications
FOR UPDATE USING (auth.uid() = user_id);

-- --------------------------------------------
-- 6.11 Page Visits Policies
-- --------------------------------------------

-- Anyone can insert page visits
CREATE POLICY "Anyone can track visits" ON public.page_visits
FOR INSERT WITH CHECK (true);

-- Admins can view all visits
CREATE POLICY "Admins can view all visits" ON public.page_visits
FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- ============================================
-- SECTION 7: FUNCTIONS & TRIGGERS
-- ============================================

-- --------------------------------------------
-- 7.1 Auto-update updated_at timestamp
-- --------------------------------------------

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tables with updated_at
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_generated_projects_updated_at
    BEFORE UPDATE ON public.generated_projects
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_service_requests_updated_at
    BEFORE UPDATE ON public.service_requests
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_websites_updated_at
    BEFORE UPDATE ON public.websites
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_domains_updated_at
    BEFORE UPDATE ON public.domains
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_dns_records_updated_at
    BEFORE UPDATE ON public.dns_records
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_domain_transactions_updated_at
    BEFORE UPDATE ON public.domain_transactions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_domain_pricing_updated_at
    BEFORE UPDATE ON public.domain_pricing
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- --------------------------------------------
-- 7.2 Auto-set full_domain for domains
-- --------------------------------------------

CREATE OR REPLACE FUNCTION set_full_domain()
RETURNS TRIGGER AS $$
BEGIN
    NEW.full_domain = NEW.domain_name || NEW.extension;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_full_domain_trigger
    BEFORE INSERT OR UPDATE ON public.domains
    FOR EACH ROW
    EXECUTE FUNCTION set_full_domain();

-- --------------------------------------------
-- 7.3 Domain expiry notifications
-- --------------------------------------------

CREATE OR REPLACE FUNCTION create_domain_expiry_notification()
RETURNS void AS $$
DECLARE
    domain_record RECORD;
BEGIN
    -- Find domains expiring in 30 days
    FOR domain_record IN
        SELECT d.id, d.user_id, d.full_domain, d.expiry_date
        FROM public.domains d
        WHERE d.status = 'active'
        AND d.expiry_date BETWEEN NOW() AND NOW() + INTERVAL '30 days'
        AND NOT EXISTS (
            SELECT 1 FROM public.domain_notifications dn
            WHERE dn.domain_id = d.id
            AND dn.notification_type = 'expiry_warning'
            AND dn.sent_at > NOW() - INTERVAL '7 days'
        )
    LOOP
        INSERT INTO public.domain_notifications (domain_id, user_id, notification_type, title, message)
        VALUES (
            domain_record.id,
            domain_record.user_id,
            'expiry_warning',
            'تنبيه: الدومين قارب على الانتهاء',
            'الدومين ' || domain_record.full_domain || ' سينتهي في ' || 
            EXTRACT(DAY FROM (domain_record.expiry_date - NOW())) || ' يوم. يرجى التجديد لتجنب فقدان الدومين.'
        );
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- SECTION 8: VIEWS FOR ANALYTICS
-- ============================================

-- --------------------------------------------
-- 8.1 Domain Statistics
-- --------------------------------------------

CREATE OR REPLACE VIEW domain_statistics AS
SELECT
    COUNT(*) as total_domains,
    COUNT(*) FILTER (WHERE status = 'active') as active_domains,
    COUNT(*) FILTER (WHERE status = 'expired') as expired_domains,
    COUNT(*) FILTER (WHERE expiry_date < NOW() + INTERVAL '30 days') as expiring_soon,
    COUNT(*) FILTER (WHERE auto_renew = true) as auto_renew_enabled,
    SUM(CASE WHEN status = 'active' THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100 as active_percentage
FROM public.domains;

-- --------------------------------------------
-- 8.2 Domain Revenue Statistics
-- --------------------------------------------

CREATE OR REPLACE VIEW domain_revenue_statistics AS
SELECT
    COUNT(*) as total_transactions,
    SUM(amount) FILTER (WHERE payment_status = 'completed') as total_revenue,
    SUM(amount) FILTER (WHERE payment_status = 'completed' AND transaction_type = 'purchase') as purchase_revenue,
    SUM(amount) FILTER (WHERE payment_status = 'completed' AND transaction_type = 'renewal') as renewal_revenue,
    AVG(amount) FILTER (WHERE payment_status = 'completed') as average_transaction_value
FROM public.domain_transactions;

-- --------------------------------------------
-- 8.3 Page Visit Statistics
-- --------------------------------------------

CREATE OR REPLACE VIEW page_visit_statistics AS
SELECT
    page_path,
    COUNT(*) as total_visits,
    COUNT(DISTINCT user_id) as unique_users,
    COUNT(DISTINCT session_id) as unique_sessions,
    COUNT(*) FILTER (WHERE device_type = 'mobile') as mobile_visits,
    COUNT(*) FILTER (WHERE device_type = 'desktop') as desktop_visits,
    MAX(visited_at) as last_visit
FROM public.page_visits
GROUP BY page_path
ORDER BY total_visits DESC;

-- ============================================
-- SECTION 9: REALTIME SUBSCRIPTIONS
-- ============================================

-- Enable realtime for important tables
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.project_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.request_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.page_visits;

-- ============================================
-- SECTION 10: INITIAL DATA
-- ============================================

-- Insert super admin (if not exists)
INSERT INTO public.admins (email, password, role)
VALUES ('oooomar123450@gmail.com', 'Omar@2597798', 'super_admin')
ON CONFLICT (email) DO NOTHING;

-- ============================================
-- COMPLETION MESSAGE
-- ============================================

DO $$
BEGIN
    RAISE NOTICE '============================================';
    RAISE NOTICE 'Database Schema Created Successfully!';
    RAISE NOTICE '============================================';
    RAISE NOTICE 'Tables Created:';
    RAISE NOTICE '  - Core: users, admins, leads, projects, news, skills, messages';
    RAISE NOTICE '  - Projects: generated_projects, project_messages, service_requests';
    RAISE NOTICE '  - Domains: domains, dns_records, domain_transactions, domain_pricing';
    RAISE NOTICE '  - Analytics: page_visits, notifications';
    RAISE NOTICE '';
    RAISE NOTICE 'RLS Policies: Enabled and Configured';
    RAISE NOTICE 'Triggers: Auto-update timestamps, domain management';
    RAISE NOTICE 'Views: Statistics and analytics views created';
    RAISE NOTICE 'Realtime: Enabled for notifications and messages';
    RAISE NOTICE '============================================';
    RAISE NOTICE 'Platform: Bacura Business (باكورة أعمال)';
    RAISE NOTICE 'Version: 2.0.0';
    RAISE NOTICE 'Date: 2026-01-13';
    RAISE NOTICE '============================================';
END $$;
