/**
 * Coder Agent Logic - محاكي منطق توليد الكود
 * يقوم بتحويل المتطلبات إلى ملفات فعلية مهيأة للتحميل
 */

import { PROJECT_TYPES, STARTER_KITS, UI_UX_RESOURCES } from '../constants/platformConstants';

class CoderAgent {
  constructor() {
    this.status = 'idle';
  }

  /**
   * محاكاة لعملية توليد المشروع
   * في النظام الحقيقي، هنا يتم الاتصال بـ OpenAI API
   */
  async generateProject(projectData) {
    this.status = 'analyzing';
    console.log("Analyzing requirements...");
    await this.delay(1500);

    this.status = 'structuring';
    console.log("Creating folder structure...");
    await this.delay(2000);

    this.status = 'coding';
    console.log("Writing core components...");
    await this.delay(3000);

    // توليد "سورس كود" تجريبي بناءً على النوع
    const projectFiles = this._getBoilerplateFiles(projectData);

    this.status = 'finalizing';
    console.log("Finalizing package & README...");
    await this.delay(1000);

    return {
      success: true,
      files: projectFiles,
      downloadUrl: "#", // سيتم استبداله برابط S3 حقيقي
      timestamp: new Date().toISOString()
    };
  }

  _getBoilerplateFiles(data) {
    const { type, description, specificAnswers, userName } = data;

    const kits = STARTER_KITS[type] || [];
    const resources = UI_UX_RESOURCES;

    const commonFiles = {
      'README.md': `# ${type.toUpperCase()} - ${userName || 'User'} Project\n\nGenerated by AI Project Builder.\n\n## Description\n${description}\n\n## Technical Stack (Recommended)\n${kits.map(k => `- [${k.name}](${k.link}): ${k.desc}`).join('\n')}\n\n## UI/UX Libraries Included\n${resources.map(r => `- [${r.name}](${r.link}): ${r.desc}`).join('\n')}\n\n## Features\n${Object.entries(specificAnswers).map(([k, v]) => `- ${k}: ${v}`).join('\n')}\n\n## Setup\nRun \`npm install\` then \`npm start\``,
      '.gitignore': 'node_modules\n.env\nbuild\ndist\n.DS_Store',
      '.env.example': 'DATABASE_URL=postgresql://user:pass@localhost:5432/db\nAPI_SECRET=your_secret_key'
    };

    if (type === PROJECT_TYPES.WEB) {
      return {
        ...commonFiles,
        'src/App.js': `import React from 'react';
import './App.css';

function App() {
  return (
    <div className="app-container">
      <header className="header">
        <h1>Welcome ${userName || ''}</h1>
        <p>This is your AI-generated project for: ${description.substring(0, 50)}...</p>
      </header>
      <main className="content">
        <section className="features">
          <h2>Project Scope</h2>
          <ul>
            ${Object.entries(specificAnswers).map(([k, v]) => `<li><strong>${k}:</strong> ${v}</li>`).join('\n            ')}
          </ul>
        </section>
      </main>
    </div>
  );
}

export default App;`,
        'src/App.css': `.app-container { font-family: sans-serif; padding: 2rem; color: #333; }
.header { border-bottom: 2px solid #3b82f6; margin-bottom: 2rem; }
.features ul { list-style: none; padding: 0; }
.features li { padding: 0.5rem 0; border-bottom: 1px solid #eee; }`,
        'package.json': JSON.stringify({
          name: "ai-web-app",
          version: "1.0.0",
          dependencies: {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "lucide-react": "^0.300.0",
            "framer-motion": "^10.16.4",
            "tailwindcss": "^3.3.0"
          },
          scripts: {
            "start": "react-scripts start",
            "build": "react-scripts build"
          }
        }, null, 2)
      };
    }

    if (type === PROJECT_TYPES.AI_BOT) {
      return {
        ...commonFiles,
        'main.py': `import os
from dotenv import load_dotenv
import openai

load_dotenv()

def start_bot():
    print("Initializing AI Bot for ${userName || 'User'}...")
    # Config: ${JSON.stringify(specificAnswers)}
    
    prompt = """
    User requirement: ${description}
    """
    
    print(f"Executing: {prompt[:50]}...")

if __name__ == "__main__":
    start_bot()`,
        'requirements.txt': 'openai>=1.0.0\npython-dotenv\nlangchain\nrequests',
        'config.yaml': `bot_settings:
  type: ${type}
  owner: ${userName}
  features: ${Object.values(specificAnswers).join(', ')}`
      };
    }

    if (type === PROJECT_TYPES.MOBILE) {
      return {
        ...commonFiles,
        'App.tsx': `import React from 'react';
import { StyleSheet, Text, View, SafeAreaView } from 'react-native';

export default function App() {
  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.card}>
        <Text style={styles.title}>Your Mobile App</Text>
        <Text style={styles.desc}>Target: ${description}</Text>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  card: { padding: 20, margin: 20, borderRadius: 15, backgroundColor: '#fff' },
  title: { fontSize: 24, fontWeight: 'bold' }
});`,
        'package.json': JSON.stringify({
          name: "ai-mobile-app",
          dependencies: { "react-native": "*" }
        }, null, 2)
      };
    }

    return commonFiles;
  }

  delay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}

export const coderAgent = new CoderAgent();
