/**
 * Utility for handling project file downloads
 */
export const downloadProjectBlueprint = (project) => {
    if (!project || !project.files) return;

    let content = `# AI Generated Project Blueprint\n`;
    content += `# Project: ${project.projectName || project.projectType || 'Untitled'}\n`;
    content += `# Generated by Omar's AI Platform\n`;
    content += `# Date: ${new Date().toLocaleDateString()}\n\n`;
    content += `> Use this file to copy-paste code or feed it into an AI coding assistant like Cursor.\n\n`;

    Object.entries(project.files).forEach(([filename, code]) => {
        const ext = filename.split('.').pop();
        content += `\n--- START OF FILE: ${filename} ---\n`;
        content += "```" + (['js', 'jsx', 'py', 'css', 'html', 'json', 'md'].includes(ext) ? ext : 'javascript') + "\n";
        content += code;
        content += "\n```\n";
        content += `--- END OF FILE: ${filename} ---\n\n`;
    });

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.style.display = 'none';
    a.href = url;
    a.download = `${(project.projectName || project.projectType || 'project').replace(/\s+/g, '_')}_blueprint.md`;

    document.body.appendChild(a);
    a.click();

    // Cleanup
    setTimeout(() => {
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
    }, 100);
};
